model_path: Qwen/Qwen2-VL-7B-Instruct
model_adapter: QwenHFVLAdapter

# Optional generation knobs the adapter will read
max_new_tokens: 512
do_sample: false

# (Optional) quantization help; if you plan to wire it in later
load_in_4bit: false
load_in_8bit: false

web_caption_prompt: |
  You are given a screenshot of a webpage. Please generate the meta web description information of this webpage, i.e., content attribute in <meta name="description" content=""> HTML element.
  You should use this format, and do not output any explanation or any other contents:
  <meta name="description" content="YOUR ANSWER">

heading_ocr_prompt: |
  You are given a screenshot of a webpage. Please generate the main text within the screenshot, which can be regarded as the heading of the webpage.
  You should directly tell me the main content, and do not output any explanation or any other contents.

element_ocr_prompt: |
  You are given a screenshot of a webpage with a red rectangle bounding box. The [x1, y1, x2, y2] coordinates of the bounding box is {bbox_ratio}.
  Please perform OCR on the bounding box and recognize the text content within the red bounding box.
  You should use the following format:
  The text content within the red bounding box is: <YOUR ANSWER>

element_ground_prompt: |
  In this website screenshot, I have labeled IDs for some HTML elements as candidates. Tell me which one best matches the description: {element_desc}
  You should directly tell me your choice in a single uppercase letter, and do not output any explanation or any other contents.

action_prediction_prompt: |
  You are given a screenshot of a webpage with a red rectangle bounding box. The [x1, y1, x2, y2] coordinates of the bounding box is {bbox_ratio}.
  Please select the best webpage description that matches the new webpage after clicking the selected element in the bounding box:
  {choices_text}
  You should directly tell me your choice in a single uppercase letter, and do not output any explanation or any other contents.
